#!/bin/bash

cd app/blender/build

PYENV=/opt/conda/envs/myenv
PYVERSION=3.7

cmake -DCMAKE_INSTALL_PREFIX=$PYENV/lib/python$PYVERSION/site-packages \
    -DWITH_PYTHON_INSTALL=OFF \
    -DWITH_PYTHON_MODULE=ON \
    -DPYTHON_ROOT_DIR=$PYENV/bin \
    -DPYTHON_SITE_PACKAGES=$PYENV/lib/python$PYVERSION/site-packages \
    -DPYTHON_INCLUDE_DIR="$PYENV/include/python${PYVERSION}m" \
    -DPYTHON_LIBRARY="$PYENV/lib/libpython${PYVERSION}m.so" \
    -DPYTHON_VERSION=$PYVERSION \
    -DWITH_INSTALL_PORTABLE=OFF \
    -DWITH_CYCLES_EMBREE=OFF \
    -DWITH_CYCLES=ON \
    -DWITH_CYCLES_DEVICE_CUDA=OFF \
    -DWITH_OPENSUBDIV=ON \
    -DWITH_OPENAL=OFF \
    -DWITH_CODEC_AVI=OFF \
    -DWITH_MOD_OCEANSIM=OFF \
    -DWITH_CODEC_FFMPEG=OFF \
    -DWITH_SYSTEM_GLEW=OFF \
    -DWITH_FFTW3=ON \
    -DWITH_OPENCOLORIO=OFF \
    -DWITH_INTERNATIONAL=OFF \
    -DWITH_BULLET=OFF \
    -DWITH_IK_SOLVER=OFF \
    -DWITH_IK_ITASC=OFF \
    -DWITH_PYTHON_INSTALL_NUMPY=OFF \
    -DWITH_MOD_FLUID=OFF \
    -DWITH_AUDASPACE=OFF \
    -DWITH_OPENCOLORIO=ON \
    -DCMAKE_BUILD_TYPE:STRING=Release ..



